### ISSUE TITLE
Typo in README setup

### ISSUE THREAD

**Issue by Fi50** [icyphy/lf-buckler#23]
I'm new to this so mayhaps I misunderstand, but is this a typo?

> Add the following to the botton of the file. The run the source command to load into current shell instance.
> 
> ```
> export PATH="$HOME/lfc_0.3.0/bin/lfc:$PATH"
> source ~/.bashrc
> ```
> 
> Replace the above $HOME/lfc_0.3.0 wiht the actual path to the version you downloaded.

At least on macOS, the command should be:
```
export PATH="$HOME/lfc_0.3.0/bin:$PATH"
source ~/.bashrc
```
In addition, might be worth pointing out that the macOS Terminal uses .bash_profile rather than .bashrc, unlike other Unix-likes.

(Sorry, not sure if it's normal opening issues for minor things lol.)

**Comment by lhstrh** [comment]
Thanks! You're right, this is a typo. I'll fix it right away and point out that macOS uses `.bash_profile`.

**Comment by Fi50** [comment]
Also, regarding the FIXME at the very top, the VMs are available [here](https://drive.google.com/drive/folders/1jN6DjV-S9AAZPqaJNieDIQ9FXOE0bkLv) (EECS149 2022 course staff).

And this part:

> If your nRF52 does not have the Buckler board mounted on it, then:
> ```
> lfc src/BuiltInLEF.lf
> ```

Should be:

```
lfc src/BuiltInLED.lf
```

**Comment by lhstrh** [comment]
Fixed!
